app1/urls.py
from django.urls import path
from app1.views import *
app_name='aa'

urlpatterns=[
    path('a1_badrinath/',a1_badrinath,name='a1_badrinath'),
    path('a1_bunny/',a1_bunny,name='a1_bunny'),
    path('a1_resugurram/',a1_resugurram,name='a1_resugurram'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='allu'

urlpatterns=[
    path('a2_dj/',a2_dj,name='a2_dj'),
    path('a2_pushpa/',a2_pushpa,name='a2_pushpa'),
    path('a2_meghana/',a2_meghana,name='a2_meghana'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def a1_badrinath(request):
    return render(request,'a1_badrinath.html')

def a1_bunny(request):
    return render(request,'a1_bunny.html')

def a1_resugurram(request):
    return render(request,'a1_resugurram.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def a2_pushpa(request):
    return render(request,'a2_pushpa.html')

def a2_meghana(request):
    return render(request,'a2_meghana.html')

def a2_dj(request):
    return render(request,'a2_dj.html')

templates/a1_badrinath.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Badrinath html page</h1>
        <h1>Badhri</h1>
        <a href="{% url 'aa:a1_bunny' %}">click to bunny html</a>
        <a href="{% url 'aa:a1_resugurram' %}">click to resugurram html</a>
    </center>
</body>
</html>

templates/a1_bunny.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>bunny html page</h1>
        <h1>Bunny AA</h1>
        <a href="{% url 'aa:a1_resugurram' %}">click to resugurram html</a>
        <a href="{% url 'aa:a1_badrinath' %}">click to badrinath html</a>
    </center>
</body>
</html>

templates/a1_resugurram.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>resugurram html page</h1>
        <h1>lucky</h1>
        <a href="{% url 'aa:a1_bunny' %}">click to bunnu html</a>
        <a href="{% url 'aa:a1_badrinath' %}">click to badrinath html</a>
    </center>
</body>
</html>

templates/a2_dj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>dj html page</h1>
        <a href="{% url 'allu:a2_meghana' %}">meghana html page</a>
        <a href="{% url 'allu:a2_pushpa' %}">pushpa html page</a>
    </center>
</body>
</html>

templates/a2_meghana.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>meghana html page</h1>
        <a href="{% url 'allu:a2_dj' %}">dj html page</a>
        <a href="{% url 'allu:a2_pushpa' %}">pushpa html page</a>
    </center>
</body>
</html>

templates/a2_pushpa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>pushpa html page</h1>
        <a href="{% url 'allu:a2_dj' %}">dj html page</a>
        <a href="{% url 'allu:a2_meghana' %}">meghana html page</a>
    </center>
</body>
</html>